name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What went wrong?
      placeholder: Describe the bug and what you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open the app
        2. Press Cmd+N
        3. Type "test"
        4. See error
    validations:
      required: true